#debug= true
defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]


[acme]
email = "thibault.coupin@gmail.com"
storage = "/etc/acme/acme.json"
entryPoint = "https"
onHostRule = true
acmeLogging = true
[acme.httpChallenge]
  entryPoint = "http"

[docker]
watch = true
domain= "thibbo.duckdns.org"


[file]
[backends]
  [backends.backend-bbox]
    [backends.backend-bbox.servers.server-bbox]
    url = "http://livebox.home"
  [backends.backend-arduino]
    [backends.backend-arduino.servers.server-arduino]
    url = "http://192.168.90.123"
[frontends]
  [frontends.frontend-bbox]
  backend = "backend-bbox"
    [frontends.frontend-bbox.routes.test_1]
    rule = "Host:box.thibbo.duckdns.org"
  [frontends.frontend-arduino]
  backend = "backend-arduino"
    [frontends.frontend-arduino.routes.hostrule]
    rule = "Host:thibbo.duckdns.org;PathPrefixStrip:/arduino"

[web]
address = ":8080"
  [web.auth.basic]
    users = ["admin:$apr1$eK5lRmZz$4uArbGwrANOy3h2CVEjAS1"]

