#debug= true
defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]


[acme]
email = "thibault.coupin@gmail.com"
storage = "/etc/acme/acme.json"
entryPoint = "https"
onDemand = true

[docker]
watch = true
domain= "thibbo.duckdns.org"

[file]
[backends]
  [backends.backend-bbox]
    [backends.backend-bbox.servers.server-bbox]
    url = "http://gestionbbox.lan"
[frontends]
  [frontends.frontend-bbox]
  backend = "backend-bbox"
    [frontends.frontend-bbox.routes.test_1]
    rule = "Host:bbox.thibbo.duckdns.org"

[web]
address = ":8080"
  [web.auth.basic]
    users = ["admin:$apr1$eK5lRmZz$4uArbGwrANOy3h2CVEjAS1"]

