#debug= true
defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
  [entryPoints.ui]
  address = ":8080"
  [entryPoints.ui.auth.basic]
    users = ["admin:$apr1$eK5lRmZz$4uArbGwrANOy3h2CVEjAS1"]

[acme]
email = "thibault.coupin@gmail.com"
storage = "/etc/acme/acme.json"
entryPoint = "https"
onHostRule = true
acmeLogging = true
[acme.httpChallenge]
  entryPoint = "http"

[docker]
watch = true
domain= "thibbo.duckdns.org"
exposedbydefault = false

[file]
  watch = true
  filename = "/etc/traefik/rules.toml"
[api]
entryPoint = "ui"

[metrics]
  [metrics.influxdb]
    address = "influxdb:8086"
    protocol = "http"
    database = "stats"
