version: "2.0"

services:

  influxdb:
    image: hypriot/rpi-influxdb:1.1.1
    volumes:
      - influxdb:/data
    ports:
      - "8086:8086"
    environment:
      ADMIN_USER: admin
      INFLUXDB_INIT_PWD: superpassword
      PRE_CREATE_DB: telegraf
    labels:
      traefik.enable: "false"
    networks:
      - influx-data
    restart: always

  grafana:
    image: dilgerm/rpi-grafana:2.6.0
    volumes:
      - grafana-data:/grafana/data
      - grafana-config:/grafana/conf
    links:
      - influxdb
    networks:
      - main_middle
      - influx-data
    labels:
      traefik.port: "3000"
      traefik.frontend.rule: "Host:stats.thibbo.duckdns.org"
      traefik.docker.network: "main_middle"
    restart: always

  telegraf:
    image: tcoupin/rpi-telegraf:1.2.1
    volumes:
      - /home/pirate/rasp-workspace/conf/telegraf:/etc/telegraf
      - /var/run/utmp:/var/run/utmp
    network_mode: host
    labels:
      traefik.enable: "false"
    depends_on:
      - influxdb
    restart: always

networks:
  influx-data:
  main_middle:
    external: true
volumes:
  influxdb:
  grafana-config:
  grafana-data:
