version: "2.0"

services:
  database:
    image: hypriot/rpi-mysql
    environment:
      MYSQL_USER: owncloud
      MYSQL_PASSWORD: mycloud
      MYSQL_DATABASE: owncloud
      MYSQL_ROOT_PASSWORD: foo
    volumes:
      - /mnt/pi2/owncloud/owncloud-db-data:/var/lib/mysql
    networks:
      - owncloud-data
    labels:
      traefik.enable: "false"
    restart: always

  owncloud:
    image: tcoupin/rpi-owncloud:10.0.2
    environment:
      OC_DBTYPE: mysql
      OC_DBPASS: mycloud
    volumes:
      - /mnt/pi2/owncloud/owncloud-data:/var/www/html/data 
      - /mnt/pi2/owncloud/owncloud-config:/var/www/html/config 
      - /mnt/pi2/owncloud/owncloud-app:/var/www/html/apps
    links:
      - "database"
    networks:
      - main_middle
      - owncloud-data
    labels:
      traefik.port: "80"
      traefik.frontend.rule: "Host:owncloud.pi2.coupin.tk, cloud.coupin.tk"
      traefik.backend: "owncloud"
      traefik.docker.network: "main_middle"
    restart: always

  owncloud-cron:
    build: ../../myImages/rpi-owncloud-cron
    networks:
      - owncloud-data
    labels:
      traefik.enable: "false"
    links:
      - "owncloud:owncloud-cron"
    tty: true
    
networks:
  owncloud-data:
  main_middle:
    external: true
