version: "2.0"

services:

  cloud:
    build:
      context: .
      dockerfile: Dockerfile.nextcloud
    volumes:
      - /data/nextcloud/data:/var/www/html/data 
      - /data/nextcloud/config:/var/www/html/config 
      - /data/nextcloud/apps:/var/www/html/apps
      - /data/nextcloud/theme:/var/www/html/themes
    networks:
      - middle
      - nextcloud
    restart: always
    labels:
      traefik.port: "80"
      traefik.frontend.rule: "Host:cloud.thibbo.duckdns.org"
      traefik.docker.network: "main_middle"
      traefik.enable: true
      traefik.frontend.redirect.permanent: 'true'
      traefik.frontend.redirect.regex: https://(.*)/.well-known/(card|cal)dav
      traefik.frontend.redirect.replacement: https://$$1/remote.php/dav/
      traefik.frontend.headers.STSSeconds: 315360000

  db:
    image: postgres:11-alpine
    restart: always
    volumes:
      - /data/nextcloud/database:/var/lib/postgresql/data
    networks:
      - nextcloud
    labels:
      traefik.enable: "false"
    environment:
      POSTGRES_USER: nc_user
      POSTGRES_PASSWORD: nc_password
      POSTGRES_DB: nc_db
    command: "-c 'shared_buffers=256MB' -c 'max_connections=200'"
  redis:
    image: redis:alpine
    restart: always
    networks:
      - nextcloud
    labels:
      traefik.enable: "false"
