version: "2.0"

services:
  camera:
    image: droogmic/rpi-cam-web
    devices:
      - /dev/vchiq
      - /dev/vcsm
    volumes:
      - /opt/vc:/opt/vc
    networks:
      - middle
    labels:
      traefik.port: "80"
      traefik.frontend.rule: "Host:camera.thibbo.duckdns.org"
      traefik.enable: true
      traefik.frontend.auth.basic.users: "admin:$$apr1$$eK5lRmZz$$4uArbGwrANOy3h2CVEjAS1"
    restart: always

