version: "2.0"

services:

  lb:
    image: arm32v6/traefik:maroilles-alpine
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data/traefik:/etc/traefik 
      - /data/acme:/etc/acme
      - /data/logs:/logs
    labels:
      traefik.port: "8080"
      traefik.enable: true
      traefik.frontend.whiteList.sourceRange: "192.168.91.0/24,192.168.90.0/24,2a01:cb1d:88bf:ba00::/64"
      traefik.frontend.whiteList.useXForwardedFor: true
      portainer: "hide"
    network_mode: host
    restart: always

  whoami:
    image: containous/whoami:latest-arm.v7
    labels:
      traefik.port: "80"
      traefik.enable: true
      traefik.frontend.rule: "Host:thibbo.duckdns.org;PathPrefixStrip:/whoami"
    networks:
      - middle


  httpd:
    image: php:apache
    labels:
      traefik.frontend.rule: "Host:thibbo.duckdns.org"
      traefik.enable: true
    depends_on: 
      - lb
    networks:
      - middle
    restart: always
    volumes:
      - /data/nextcloud/data/tcoupin/files/www:/var/www/html:ro

  camera:
    extends:
      file: docker-compose.camera.yml
      service: camera

  cloud:
    extends:
      file: docker-compose.nextcloud.yml
      service: cloud
    links:
      - cloud-db
      - cloud-cache

  cloud-db:
    extends:
      file: docker-compose.nextcloud.yml
      service: db
  cloud-cache:
    extends:
      file: docker-compose.nextcloud.yml
      service: redis

networks:
  middle:
  nextcloud:
