version: "2.0"

services:

  cloud:
    build:
      context: .
      dockerfile: Dockerfile.nextcloud
    volumes:
      - /mnt/pi3/nextcloud/data:/var/www/html/data 
      - /mnt/pi3/nextcloud/config:/var/www/html/config 
      - /mnt/pi3/nextcloud/apps:/var/www/html/apps
      - /mnt/pi3/nextcloud/theme:/var/www/html/themes
    networks:
      - middle
    labels:
      traefik.port: "80"
      traefik.frontend.rule: "Host:cloud.thibbo.duckdns.org"
      traefik.docker.network: "main_middle"
      traefik.enable: true
    restart: always


#  owncloud-cron:
#    build: ../../myImages/rpi-owncloud-cron
#    networks:
#      - owncloud-data
#    labels:
#      traefik.enable: "false"
#    links:
#      - "owncloud:owncloud-cron"
#    tty: true

